### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by fabiojansenbr** [nathansdev/ContraFlutterKit#14]
Im trying to run the project but im getting gradle errors:

* Where:
Build file 'C:\Users\fabio\Desktop\ContraFlutterKit\android\app\build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

My flutter version is 1.22.0

How to fix this?

**Comment by Dasunx** [comment]
Goto -> 'C:\Users\fabio\Desktop\ContraFlutterKit\android\app\build.gradle' line: 60
and replace
```
storeFile file(keystoreProperties['storeFile'])
```

using
```
storeFile file("key.jks")  
```

**Comment by Dasunx** [comment]
@nathansdev can you close this issue?

**Comment by nathansdev** [comment]
Sorry, @Dasunx I did not see the notification for long time,
Closing now.
