### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by thamiiaz** [nathansdev/ContraFlutterKit#16]
When trying to execute, the following errors were reported (repeatedly, several of them)
**../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/render_picture.dart:20:9: Error: Type 'PictureInfo' not found.
  final PictureInfo picture;**

**lib/login/login_form_one.dart:33:23: Error: The getter 'SvgPicture' isn't defined for the class 'LoginFormTypeOne'.
 - 'LoginFormTypeOne' is from 'package:contraflutterkit/login/login_form_one.dart' ('lib/login/login_form_one.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SvgPicture'.
                      SvgPicture.asset(
                      ^^^^^^^^^^**

**../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/render_picture.dart:20:9: Error: 'PictureInfo' isn't a type.
  final PictureInfo picture;
        ^^^^^^^^^^^**

_**### attached the execution log**_

[LOG-02172021.txt](https://github.com/nathansdev/ContraFlutterKit/files/5996068/LOG-02172021.txt)

**Comment by zikwall** [comment]
I support it, here are some more examples of some problems when trying to run on the device

```
/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.

class PictureStream with DiagnosticableMixin {

                         ^^^^^^^^^^^^^^^^^^^
```

```              
/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.

    super.debugFillProperties(properties);

          ^^^^^^^^^^^^^^^^^^^

```

and they all seem to be related to the `flutter_svg-0.17.4` dependency

**Comment by aniketambore** [comment]
Hello, You can just replace the `flutter_svg: ^0.17.4` with `flutter_svg: ^0.19.3` and that's working fine.
